version: '3.9'
services:
  api:
    build: ./apps/api
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
  web:
    build: ./apps/web
    ports:
      - "3000:3000"
    depends_on:
      - api
  worker:
    build: ./apps/worker
    depends_on:
      - redis
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
